log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":8000"

http:
  routers:
    web-router:
      rule: "Host(`localhost`)"

      entryPoints:
        - web
      service: django

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
